### ISSUE TITLE
Git Usage out of remote Workspace

### ISSUE THREAD

**Issue by trevorkloz** [mkloubert/vscode-remote-workspace#11]
Hi,

this extension is a real helper! 

I'm remotely connected to a VM with all code and SCM (git) inside. And here starts the problem. All git commands must be made inside the VM. Unfortunately I cannot use the git functionality from inside VS Code. 

Is it possible to make scm and scode-remote-workspace work together?

Thanks!

**Comment by mkloubert** [comment]
@trevorkloz 

Unfortunately this will not be possible the integrated VSCode way, because the IDE uses the official, local [git CLI](https://git-scm.com/downloads) of the operating system, what means you need to provide your repo locally.

The new [FileSystemProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemProvider) only supports read and write operations, but nothing to execute.

Do you use SFTP? If so, we should be able to use the internal supported feature to run any command of the host via [SFTP](https://www.npmjs.com/package/ssh2-sftp-client), with the user, you are currently connected to the server.

My idea is to provide GUI functions of VSCode (like an input box or virtual terminal), where you can input git commands, which are send to the server and executed there.

**Comment by trevorkloz** [comment]
@mkloubert 

Yes, I'm using sftp. Do you mean there is a method, that I can use now via configuration - or that it can be coded in principle? 

Thanks in advance,
TK

**Comment by mkloubert** [comment]
@trevorkloz 

**I have released a new version 0.26.0**, which is now able to run git commands on a SFTP server.

You have to execute new `Remote Workspace: Execute 'git' Command ...` VSCode command for that:

![demo2](https://user-images.githubusercontent.com/4951215/41371043-809a8062-6f49-11e8-8498-aba4ab1e2736.gif)

You are also able to run any other shell or server command by executing `Remote Workspace: Execute Remote Command ...`
This works for [FTP](https://github.com/mkloubert/vscode-remote-workspace#ftp-), [secure FTPS](https://github.com/mkloubert/vscode-remote-workspace#sftps-) and [SFTP](https://github.com/mkloubert/vscode-remote-workspace#sftp-).

**Comment by mkloubert** [comment]
@trevorkloz 

**If you have problems**, as described in [issue #16](https://github.com/mkloubert/vscode-remote-workspace/issues/16), **they should be fixed since version 0.26.1.**

**Comment by trevorkloz** [comment]
Works fine for me for now. Thanks!

**Comment by kooliebwoy** [comment]
Any plans on making this extension allow upload of an image. Through drag n drop from windows or copy and paste?
