### ISSUE TITLE
Formatter not working with vscode-remote-workspace

### ISSUE THREAD

**Issue by bmocha** [mkloubert/vscode-remote-workspace#29]
Thanks for this extremely useful extension!

I have vscode-remote-workspace working perfectly with the editor running on macOS and the project files located on a Linux server over sftp. I have the Python extension ms-python.python installed and its variables have been configured to use autopep8 to format the file on save.

Formatting works fine while editing in a local workspace on the Mac.
Formatting on save does not work when saving remote-workspace files - files are saved without running the formatter.
Explicitly trying to format via Option-Shift-F produces a message:
"There is no document formatter for 'python'-files installed."

This is not a problem with formatter installation. If I open a local workspace at the same time, formatting works.

It would be extremely useful for formatting to work with a remote-workspace where the formatter just runs on the local machine and saves to the remote system. Since the edited file is remote, git submission happens from the remote system and having the pushed file be properly formatted is valuable.

-------------------------------------------------------------

Versions:
VS Code: Version 1.23.1 (1.23.1)
ms-python.python: 2018.6.0
mkloubert.vscode-remote-workspace: 0.30.2

Config:
// Controls if the editor should automatically format the pasted content. A formatter must be available and the formatter should be able to format a range in a document.
  "editor.formatOnPaste": true,
  // Format a file on save. A formatter must be available, the file must not be auto-saved, and editor must not be shutting down.
  "editor.formatOnSave": true,
  // Format on save timeout. Specifies a time limit in milliseconds for formatOnSave-commands. Commands taking longer than the specified timeout will be cancelled.
  "editor.formatOnSaveTimeout": 3000,

**Comment by mkloubert** [comment]
@bmocha 

I think the problem is, that your formatter is not able to handle the new [FileSystemProvider API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemProvider). This is why it is working locally and not for remote files.

The extension only supports low-level file system support, and formatting is the job of external formatters.

I currently have no chance of executing the feature manually, because I get the data which is unformatted and an external formatter has to support other URI schemes, which is currently not possible.

There is already an [issue](https://github.com/Microsoft/vscode/issues/51528), I have opened in [vscode project](vscode).

Your issue seems to be similar to [linting and formatting](https://github.com/mkloubert/vscode-remote-workspace/issues/2).

**Comment by efreibe** [comment]
Hello, any advance on this? Is this the new API that you were talking about or another API exists by this time?

https://github.com/microsoft/vscode/issues/48034#issuecomment-513726722
