### ISSUE TITLE
Prompt for key phrase

### ISSUE THREAD

**Issue by 7twin** [mkloubert/vscode-remote-workspace#3]
Is there any way to prompt for password rather than saving it in clear text inside the project file? I tried to force `tryKeyboard` by supplying a wrong password and key, but that has no effect

**Comment by mkloubert** [comment]
@7twin 

As explained [here](https://github.com/mkloubert/vscode-remote-workspace/issues/1#issuecomment-390501455) and [here](https://github.com/mkloubert/vscode-remote-workspace/issues/1#issuecomment-390506878), this is an internal, non interactive thing of the [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) module, I use.

**If logging in with username and password**, you can use the `auth` parameter for that:

1. Create a file like `sftp_server1` inside your home directory and save your username and password there, like in an URI: `USERNAME:PASSWORD`
2. Add the `auth` parameter to your URI: `auth=sftp_server1`

**If you use a key file with a passphrase**, you can do the same thing by setting up the `phrase` parameter as path to a file, that contains that phrase.

**Comment by mkloubert** [comment]
@7twin 

Yes, but it moves it from the visible URI to an external file.

The problem is that VS Code runs a lot of background operations, when using the new FileSystem API (looking for `.vscode` and `node_modules` subfolders), which can produce some conflicts (double display of password prompts, e.g.).

The aim of that extension is simply to handle URIs and the settings / parameter in them, without interacting with a GUI or workspace (settings).

I will try to find a soulution for that.

**Comment by 7twin** [comment]
I'll close it for now then, thanks
