### ISSUE TITLE
Can there be a "/" symbol in FTP account?

### ISSUE THREAD

**Issue by AShujiao** [mkloubert/vscode-remote-workspace#5]
FTP account: abc/style, this type of account will be unable to connect to me. Please confirm. I'm "@" bug

**Comment by mkloubert** [comment]
@AShujiao 

This is possible, but you have to do this another way, because the [VS Code URI parser](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Uri) gets problems, when using an URI like that: `ftp://abc/style:password@server:21/path/to/root/folder`:

Create a text file like `my_ftp_server` inside your home directory and write your credentials there: `abc/style:password`

Change your URI to something like that: `ftp://server:21/path/to/root/folder?auth=my_ftp_server`

**Comment by AShujiao** [comment]
Tried your method, but there was still a problem, prompting "530 Log in with USER and PASS first" what is the reason? Is the `my_ftp_server` file the same directory as the `workspace` file? My uri:`ftp://abc.style.com:21/? Auth=my_ftp_server`

**Comment by mkloubert** [comment]
@AShujiao 

The home directory is the directory of the current user, like `C:\Users\AShujiao` (Windows) or `/Users/AShujiao` (Mac).
