### ISSUE TITLE
FTP should support FTPS connection

### ISSUE THREAD

**Issue by hajekj** [mkloubert/vscode-remote-workspace#6]
I think it is super important to have FTP connection support FTPS mode so the connection to the remote server can be encrypted and secure.

I think it is very important to be able to have secure connection to the server in today's world.

**Comment by hajekj** [comment]
Additionally, it doesn't seem like ftpjs supports SSL connection, I suggest replacing it by ftp package (https://www.npmjs.com/package/ftp) which supports explicit secure connection and much more FTP options.

**Comment by mkloubert** [comment]
@hajekj 

**Since version 0.24.0, the FTPS protocol is implemented.**

Example:

```json
{
    "folders": [{
        "uri": "ftps://my-user:my-password@ftps.example.com/",
        "name": "My (secure) FTP folder"
    }],
    "settings": {}
}
```

**Comment by mkloubert** [comment]
@hajekj 

The reason why I use [jsftp](https://github.com/sergi/jsftp) instead of [node-ftp](https://github.com/mscdex/node-ftp) is, as you can read [here](https://github.com/mscdex/node-ftp/issues/180), that downloading files not always works ... it often returns zero data of files, even if I use the described workarrounds.

But as you can read in [that issue](https://github.com/mscdex/node-ftp/issues/203), @icetee has created a good working [fork](https://www.npmjs.com/package/@icetee/ftp), which solves that and other problems.

Please let me known, if the new feature works for you.

**Comment by hajekj** [comment]
Amazing job!
